name: music_player
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  flutter_launcher_icons: ^0.5.2
  url_launcher: ^3.0.3
  path_provider: "^0.4.1"
  audioplayer: ^0.5.0
  local_notifications: ^0.0.7
  dynamic_theme:
      git:
        url: git://github.com/Norbert515/dynamic_theme.git

flutter_icons:
  android: true
  ios: true
  image_path: "img/placeholder.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - img/placeholder.png
